export interface Job {
  id: string;
  title: string;
  company: string;
  technologies: string[];
  location: string;
  category: 'Backend' | 'Frontend' | 'Fullstack' | 'Data Science' | 'Mobile' | 'DevOps' | 'Design' | 'QA' | 'Support';
  description: string;
  postedAt: string;
  url: string;
  source?: 'CIEE' | 'IEL' | 'Startup' | 'Direct' | 'Erasmus+' | 'Parker Dewey' | 'LinkedIn' | 'Indeed';
  code?: string;
  contactEmail?: string;
  isRemote?: boolean;
}

export interface News {
  id: string;
  title: string;
  source: string;
  url: string;
  publishedAt: string;
  category: 'Manaus' | 'Brasil' | 'International';
  summary: string;
}

export const MOCK_JOBS: Job[] = [
  {
    id: 'int1',
    title: 'Software Engineering Intern (Remote)',
    company: 'Tech Giant USA',
    technologies: ['Python', 'Go', 'Kubernetes'],
    location: 'Remote (USA)',
    category: 'Backend',
    description: 'Join a world-class engineering team in the USA. Remote opportunity for international students.',
    postedAt: '2026-03-12',
    url: 'https://www.linkedin.com/jobs/search/?keywords=Software+Engineering+Intern+Remote+USA',
    source: 'LinkedIn',
    isRemote: true,
  },
  {
    id: 'int2',
    title: 'Micro-Internship: Web Development',
    company: 'Parker Dewey Projects',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    location: 'Remote (USA)',
    category: 'Frontend',
    description: 'Short-term, paid professional assignments in the USA. Great for building your portfolio.',
    postedAt: '2026-03-11',
    url: 'https://www.parkerdewey.com/',
    source: 'Parker Dewey',
    isRemote: true,
  },
  {
    id: 'int3',
    title: 'Fullstack Developer Intern (Erasmus+)',
    company: 'EuroTech Solutions',
    technologies: ['Vue.js', 'PHP', 'MySQL'],
    location: 'Remote (Europe)',
    category: 'Fullstack',
    description: 'Internship opportunity through the Erasmus+ program. Work with a European startup remotely.',
    postedAt: '2026-03-10',
    url: 'https://erasmusintern.org/traineeships',
    source: 'Erasmus+',
    isRemote: true,
  },
  {
    id: 'int4',
    title: 'Data Analyst Intern (Remote Europe)',
    company: 'Berlin Data Labs',
    technologies: ['Python', 'SQL', 'Tableau'],
    location: 'Remote (Germany)',
    category: 'Data Science',
    description: 'Analyze complex datasets for a leading data lab in Berlin. Remote work allowed.',
    postedAt: '2026-03-12',
    url: 'https://de.indeed.com/jobs?q=Data+Analyst+Intern+Remote',
    source: 'Indeed',
    isRemote: true,
  },
  {
    id: 'm1',
    title: 'Estágio em Desenvolvimento Web',
    company: 'Manaus Tech Hub',
    technologies: ['React', 'Node.js', 'JavaScript'],
    location: 'Manaus, AM',
    category: 'Fullstack',
    description: 'Oportunidade em uma das maiores aceleradoras de startups da região norte.',
    postedAt: '2026-03-12',
    url: 'https://manaustechhub.com/',
    source: 'Startup',
    contactEmail: 'talentos@manaustechhub.com',
  },
  {
    id: 'm2',
    title: 'Estagiário de TI (Suporte e Redes)',
    company: 'CIEE Manaus',
    technologies: ['Windows Server', 'Linux', 'Redes'],
    location: 'Manaus, AM',
    category: 'Support',
    description: 'Vaga via CIEE para atuação em órgão público em Manaus.',
    postedAt: '2026-03-11',
    url: 'https://web.ciee.org.br/estudante/processos-seletivos-lista',
    source: 'CIEE',
    code: '05128934',
  },
  {
    id: 'r1',
    title: 'Estágio Backend Node.js (Remoto)',
    company: 'CloudScale Brasil',
    technologies: ['Node.js', 'TypeScript', 'AWS'],
    location: 'Remoto',
    category: 'Backend',
    description: 'Trabalhe de qualquer lugar do Brasil em uma startup focada em escalabilidade cloud.',
    postedAt: '2026-03-12',
    url: 'https://www.linkedin.com/jobs/search/?keywords=CloudScale+Brasil+Backend',
    source: 'Startup',
    isRemote: true,
    contactEmail: 'jobs@cloudscale.com.br',
  },
  {
    id: 'r2',
    title: 'Estágio Frontend React (Remoto)',
    company: 'Digital Ocean Partners',
    technologies: ['React', 'Tailwind CSS', 'Figma'],
    location: 'Remoto',
    category: 'Frontend',
    description: 'Vaga 100% remota para estudantes de todo o Brasil. Foco em interfaces modernas.',
    postedAt: '2026-03-11',
    url: 'https://www.linkedin.com/jobs/search/?keywords=Digital+Ocean+Partners+Frontend',
    source: 'Direct',
    isRemote: true,
    contactEmail: 'rh@digitaloceanpartners.io',
  },
  {
    id: 'sp1',
    title: 'Estágio em QA / Testes',
    company: 'TechJunction SP',
    technologies: ['Selenium', 'Cypress', 'JavaScript'],
    location: 'São Paulo, SP',
    category: 'QA',
    description: 'Oportunidade presencial em São Paulo para atuar com automação de testes.',
    postedAt: '2026-03-12',
    url: 'https://www.linkedin.com/jobs/search/?keywords=TechJunction+SP+QA',
    source: 'Direct',
    contactEmail: 'vagas@techjunction.com.br',
  },
  {
    id: 'm3',
    title: 'Estágio em Desenvolvimento Java',
    company: 'Samsung Ocean Manaus',
    technologies: ['Java', 'Android', 'Kotlin'],
    location: 'Manaus, AM',
    category: 'Backend',
    description: 'Participe de projetos de inovação tecnológica no ecossistema Samsung.',
    postedAt: '2026-03-10',
    url: 'https://www.oceanbrasil.com/',
    source: 'Direct',
  },
  {
    id: 'm4',
    title: 'Estágio em Análise de Dados',
    company: 'IEL Amazonas',
    technologies: ['Excel Avançado', 'Power BI', 'SQL'],
    location: 'Manaus, AM',
    category: 'Data Science',
    description: 'Vaga de estágio via IEL para indústria no Distrito Industrial.',
    postedAt: '2026-03-12',
    url: 'https://iel-am.org.br/estagio/vagas-de-estagio',
    source: 'IEL',
    code: 'IEL-2026-042',
  },
  {
    id: 'p1',
    title: 'Estágio em Desenvolvimento (PRODAM)',
    company: 'Governo do Amazonas - PRODAM',
    technologies: ['Java', 'Spring Boot', 'SQL'],
    location: 'Manaus, AM',
    category: 'Backend',
    description: 'Estágio no órgão de Processamento de Dados do Amazonas. Atuação em sistemas governamentais estaduais.',
    postedAt: '2026-03-12',
    url: 'https://www.prodam.am.gov.br/',
    source: 'Direct',
  },
  {
    id: 'p2',
    title: 'Estágio em TI - Suporte e Redes',
    company: 'Prefeitura de Manaus - SEMAD',
    technologies: ['Hardware', 'Redes', 'Windows'],
    location: 'Manaus, AM',
    category: 'Support',
    description: 'Oportunidade na Secretaria Municipal de Administração. Suporte técnico aos órgãos municipais.',
    postedAt: '2026-03-11',
    url: 'https://manaus.am.gov.br/',
    source: 'CIEE',
    code: 'MUN-2026-088',
  },
  {
    id: 'rj1',
    title: 'Estágio em Mobile (iOS/Android)',
    company: 'Carioca Tech',
    technologies: ['Swift', 'Kotlin', 'Flutter'],
    location: 'Rio de Janeiro, RJ',
    category: 'Mobile',
    description: 'Vaga presencial no Rio de Janeiro para desenvolvimento de aplicativos nativos e híbridos.',
    postedAt: '2026-03-10',
    url: 'https://www.linkedin.com/jobs/search/?keywords=Carioca+Tech+Mobile',
    source: 'Startup',
    contactEmail: 'recrutamento@cariocatech.com.br',
  },
  {
    id: 'p3',
    title: 'Estágio em Desenvolvimento Web (TRT11)',
    company: 'Tribunal Regional do Trabalho - 11ª Região',
    technologies: ['PHP', 'Laravel', 'JavaScript'],
    location: 'Manaus, AM',
    category: 'Fullstack',
    description: 'Vaga federal no TRT11 (AM/RR). Desenvolvimento e manutenção de sistemas judiciários.',
    postedAt: '2026-03-10',
    url: 'https://portal.trt11.jus.br/',
    source: 'Direct',
  },
  {
    id: 'p4',
    title: 'Estágio em Ciência de Dados (UFAM)',
    company: 'Universidade Federal do Amazonas',
    technologies: ['Python', 'R', 'Estatística'],
    location: 'Manaus, AM',
    category: 'Data Science',
    description: 'Oportunidade em laboratórios de pesquisa e inovação da UFAM.',
    postedAt: '2026-03-12',
    url: 'https://ufam.edu.br/',
    source: 'Direct',
  },
  {
    id: 'p5',
    title: 'Estagiário de Desenvolvimento Mobile',
    company: 'UEA - Universidade do Estado do Amazonas',
    technologies: ['Flutter', 'Dart', 'Firebase'],
    location: 'Manaus, AM',
    category: 'Mobile',
    description: 'Atuação em projetos de extensão e desenvolvimento de apps na UEA.',
    postedAt: '2026-03-09',
    url: 'https://uea.edu.br/',
    source: 'Direct',
  },
  {
    id: 'p6',
    title: 'Estágio em Infraestrutura e Cloud',
    company: 'IFAM - Instituto Federal do Amazonas',
    technologies: ['Linux', 'Docker', 'Redes'],
    location: 'Manaus, AM',
    category: 'DevOps',
    description: 'Vaga federal para suporte à infraestrutura de rede e servidores do IFAM.',
    postedAt: '2026-03-08',
    url: 'http://www.ifam.edu.br/',
    source: 'Direct',
  },
  {
    id: 'p7',
    title: 'Estágio em TI (TRE-AM)',
    company: 'Tribunal Regional Eleitoral do Amazonas',
    technologies: ['Suporte', 'Sistemas', 'Segurança'],
    location: 'Manaus, AM',
    category: 'Support',
    description: 'Vaga federal no TRE-AM. Apoio técnico especializado em sistemas eleitorais.',
    postedAt: '2026-03-12',
    url: 'https://www.tre-am.jus.br/',
    source: 'IEL',
    code: 'FED-TRE-2026',
  },
  {
    id: 'r3',
    title: 'Estágio em Data Science (Remoto)',
    company: 'DataViz Brasil',
    technologies: ['Python', 'Pandas', 'Tableau'],
    location: 'Remoto',
    category: 'Data Science',
    description: 'Vaga remota para estudantes de estatística ou computação. Foco em visualização de dados.',
    postedAt: '2026-03-12',
    url: 'https://www.linkedin.com/jobs/search/?keywords=DataViz+Brasil+Data+Science',
    source: 'Startup',
    isRemote: true,
    contactEmail: 'career@dataviz.com.br',
  },
  {
    id: 'bh1',
    title: 'Estagiário de DevOps',
    company: 'Mineiro Tech',
    technologies: ['Docker', 'Kubernetes', 'CI/CD'],
    location: 'Belo Horizonte, MG',
    category: 'DevOps',
    description: 'Oportunidade presencial em BH para atuar com automação de infraestrutura.',
    postedAt: '2026-03-11',
    url: 'https://www.linkedin.com/jobs/search/?keywords=Mineiro+Tech+DevOps',
    source: 'Direct',
    contactEmail: 'rh@mineirotech.com.br',
  },
  {
    id: 'p8',
    title: 'Estágio em Desenvolvimento (SEMIT)',
    company: 'Secretaria Municipal de Inovação e Tecnologia',
    technologies: ['React', 'Node.js', 'API'],
    location: 'Manaus, AM',
    category: 'Fullstack',
    description: 'Vaga municipal na SEMIT Manaus. Foco em digitalização de serviços públicos.',
    postedAt: '2026-03-12',
    url: 'https://semit.manaus.am.gov.br/',
    source: 'Direct',
    contactEmail: 'estagio@semit.manaus.am.gov.br',
  },
];

export const MOCK_NEWS: News[] = [
  {
    id: 'n1',
    title: 'Manaus Tech Hub anuncia nova rodada de aceleração para startups locais',
    source: 'A Crítica',
    url: 'https://www.acritica.com/manaus',
    publishedAt: '2026-03-12',
    category: 'Manaus',
    summary: 'Aceleradora do Sidia busca novos talentos e soluções inovadoras na região norte.',
  },
  {
    id: 'n2',
    title: 'Polo Industrial de Manaus registra alta na demanda por profissionais de TI',
    source: 'G1 Amazonas',
    url: 'https://g1.globo.com/am/amazonas/',
    publishedAt: '2026-03-10',
    category: 'Manaus',
    summary: 'Indústrias do Distrito Industrial buscam estagiários e desenvolvedores para digitalização.',
  },
  {
    id: 'n3',
    title: 'Mercado de tecnologia no Brasil deve crescer 12% em 2026, aponta relatório',
    source: 'Canaltech',
    url: 'https://canaltech.com.br/mercado/',
    publishedAt: '2026-03-11',
    category: 'Brasil',
    summary: 'Setor de software e serviços continua sendo o principal motor da economia digital.',
  },
  {
    id: 'n4',
    title: 'CIEE e IEL abrem mais de 500 vagas de estágio em tecnologia nesta semana',
    source: 'Exame',
    url: 'https://exame.com/carreira/',
    publishedAt: '2026-03-12',
    category: 'Brasil',
    summary: 'Oportunidades estão espalhadas por todo o país, com foco em trabalho híbrido e remoto.',
  },
  {
    id: 'n5',
    title: 'Startup amazonense recebe aporte milionário para expansão nacional',
    source: 'Portal Holanda',
    url: 'https://www.portalholanda.com.br/tecnologia/',
    publishedAt: '2026-03-09',
    category: 'Manaus',
    summary: 'Empresa focada em logística na Amazônia atrai investidores do sudeste.',
  },
  {
    id: 'n6',
    title: 'Novas regras para estágio em TI entram em vigor no Brasil',
    source: 'Valor Econômico',
    url: 'https://valor.globo.com/carreira/',
    publishedAt: '2026-03-08',
    category: 'Brasil',
    summary: 'Mudanças visam garantir melhor formação técnica e benefícios para os estudantes.',
  },
  {
    id: 'n7',
    title: 'Top 10 Platforms for International Remote Internships in 2026',
    source: 'TechCrunch',
    url: 'https://techcrunch.com/',
    publishedAt: '2026-03-12',
    category: 'International',
    summary: 'Discover the best websites to find remote internships in the USA, Europe, and Asia.',
  },
  {
    id: 'n8',
    title: 'Erasmus+ Program Expands Remote Traineeship Opportunities',
    source: 'European Commission',
    url: 'https://ec.europa.eu/programmes/erasmus-plus/',
    publishedAt: '2026-03-11',
    category: 'International',
    summary: 'New funding available for students seeking digital internships across European borders.',
  },
];
